import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('kc-house-data.csv')

plt.figure(figsize = (10, 6))
plt.hist(data['price'], bins=30, edgecolor = 'black')
plt.title('Распределение цен на недвижимость')
plt.xlabel('Цена (USD)')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
plt.hist(data['sqft_living'], bins=30, edgecolor = 'black')
plt.title('Распределение жилой площади')
plt.xlabel('Жилая площадь (sqft)')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
plt.hist(data['yr_built'], bins=30, edgecolor = 'black')
plt.title('Распределение года постройки')
plt.xlabel('Год постройки')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
data['waterfront'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение домов по наличию вида на набережную')
plt.xlabel('Вид на набережную')
plt.ylabel('Количество домов')
plt.xticks([0, 1], ['Нет', 'Да'], rotation=0)
plt.grid(axis='y')
plt.show()

plt.figure(figsize = (10, 6))
data['floors'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение домов по количеству этажей')
plt.xlabel('Количество этажей')
plt.ylabel('Количество домов')
plt.grid(axis='y')
plt.show()

plt.figure(figsize = (10, 6))
data['condition'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение состояния домов')
plt.xlabel('Состояние домов')
plt.ylabel('Количество домов')
plt.grid(axis='y')
plt.show()